### ISSUE TITLE
1.7.10 - Skeletons spawn even when on peaceful mode Difficulty 0

### ISSUE THREAD

**Issue by ProsperCraft** [Tyler1555/Mini-Bosses#4] opened 2016-06-28 15:30 UTC
I am pregenerating my world on the FTB presents Crackpack 2 modpack, and I had 200,000 skeletons even on peaceful mode.

**Comment by Tyler1555** [comment] 2016-06-28 23:36
Mobs spawning out of control was fixed in release 1.2.8 for Minecraft 1.8. This mod never messed with vanilla spawn rates so something else is probably causing the issue. I'd use CoFH core to get rid of the skeletons. Also make sure you are using the latest version for 1.7.10, Github sorted them out of order for some reason so compare version numbers.

**Comment by phit** [comment] 2016-06-29 21:26
can you please backport the fix for 1.7.10?

**Comment by ProsperCraft** [comment] 2016-06-29 22:21
Yes, please...your mod was recently included in a popular pack called Crackpack and it will have many players, disabling the mod because it is creating tens to hundreds of thousands of mobs isn't an option because then the clients crash when they try to log in with the mod.

Cofh killall will not kill them, essentials killall will not kill them, clearlag kill will not kill them.  It says it does and if you repeat the command it says it does again, but they remain.

**Comment by ProsperCraft** [comment] 2016-06-29 22:28
http://www.feed-the-beast.com/projects/ftb-presents-crackpack

**Comment by Tyler1555** [comment] 2016-06-29 22:30
Damn, never though I would make it into an FTB default pack. I'll start looking into this issue.

**Comment by Tyler1555** [comment] 2016-06-29 23:06
I couldn't reproduce the issue using the mod standalone or using the pack. I've reached out to the Mindcrack team to try to get some help with this. Until then, please post the config settings for your server if they deviate from the pack, any mods you are using that are not default in the pack, and any mods/scripts you use to change the mod such as Minetweaker. Also if the issue is only occurring in one chunk, that could be a sign that the chunk is corrupted.

**Comment by ProsperCraft** [comment] 2016-06-29 23:14
Download this and run it in place of forge.
https://github.com/CyberdyneCC/Thermos/releases

It has many optimizations, and allows bukkit plugins.

We have not changed the pack configs at all.

After running, we started a world pregen using worldborder- 
http://dev.bukkit.org/bukkit-plugins/worldborder/

you set the border on the world /wb set 2000(we did 10k), generate the world, /wb fill 100  so that there is less lag when you have players running all over looking for a place to live.

we have a plugin that notifies us if there are too many entities in a chunk...you can find them with /cofh killall  eventually you end up finding there are 30k skeletons that won't die from /cofh killall

**Comment by ProsperCraft** [comment] 2016-06-29 23:15
If you want, I can just dropbox you a working server directory.

**Comment by Tyler1555** [comment] 2016-06-29 23:17
> We have a plugin that notifies us if there are too many entities in a chunk...you can find them with /cofh killall eventually you end up finding there are 30k skeletons that won't die from /cofh killall

Does the plugin say that they are all in one chunk?

**Comment by ProsperCraft** [comment] 2016-06-29 23:20
yes
I had considered deleting that region file.

**Comment by ProsperCraft** [comment] 2016-06-29 23:20
its not just once this happened though, its been more then once.

**Comment by Tyler1555** [comment] 2016-06-29 23:23
That chunk is probably corrupted. Move the world files to a different directory and try generating a new world.

**Comment by Tyler1555** [comment] 2016-07-05 02:33
Since it has been 5 days since the person who opened the issue last responded, and the issue is likely due to a chunk being corrupted or a Thermos issue (both of which are out of my control), and under stable conditions the issue cannot be reproduced, I am closing this issue and considering it solved.

**Closed as completed by Tyler1555** 2016-07-05 02:33 UTC
Labels: invalid
